// User Types
const IUT1 = "ISO_USER_TYPE_1";
const IUT2 = "ISO_USER_TYPE_2";
const IUT3 = "ISO_USER_TYPE_3";
const IUT4 = "ISO_USER_TYPE_4";

// Role Levels
const L1 = "HAND_OFF";
const L2 = "HAND_HOLDERS";
const L3 = "HAND_ON_NICHE"
const L4 = "HAND_ON_ALL_VERTICALS";

// Roles
var R1 = IUT1 + L1;
var R1 = IUT1 + L2 + L3;

console.log(R1);


function constIUT1() {

};
function constIUT2() {

};
function constIUT3() {

};
function constIUT4() {

};





// PRODUCT TAXONOMY AND DATA LOGIC

LAMPS
	-- SHARED CATEGORIES
	-- UNIQUE TO LAMP CATEGORIES

KITS
	-- SHARED CATEGORIES
	-- UNIQUE TO KITS CATEGORIES

FIXTURES
	-- SHARED CATEGORIES
	-- UNIQUE TO FIXTURES CATEGORIES

ACCESSORIES*
	-- 



RULE: YOU MAY CHOOSE TO USE A FIXTURE OVER KIT DEPENDING ON A ROCK, PAPER, SCISSORS - WHICHEVER MAKES MORE SENSE GIVEN A SCENARIO

RULE: SHIPPING, REBATES AND LOGISTICS MAY DICTATE WHICH OF THE ABOVE CATEGORIES YOU CHOOSE IN A GIVEN SITUATION

